services:
  user-db:
    image: postgres:16
    container_name: chat-youapp-user-db
    environment:
      POSTGRES_DB: ${USER_DB_NAME:-chat_youapp_user_service}
      POSTGRES_USER: ${USER_DB_USER:-chat_youapp_user_user}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD:-chat_youapp_user_password}
    ports:
      - '${USER_DB_PORT:-5432}:5432'
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - chat-youapp-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: chat-youapp-rabbitmq
    ports:
      - '${RABBITMQ_PORT:-5672}:5672'
      - '${RABBITMQ_MANAGEMENT_PORT:-15672}:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    networks:
      - chat-youapp-network
  auth-db:
    image: mysql:8.0
    container_name: chat-youapp-auth-db
    environment:
      MYSQL_DATABASE: ${AUTH_DB_NAME:-chat_youapp_auth_service}
      MYSQL_USER: ${AUTH_DB_USER:-chat_youapp_auth_user}
      MYSQL_PASSWORD: ${AUTH_DB_PASSWORD:-chat_youapp_auth_password}
      MYSQL_ROOT_PASSWORD: ${AUTH_DB_ROOT_PASSWORD:-root_password}
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password']
    ports:
      - '${AUTH_DB_PORT:-3306}:3306'
    volumes:
      - auth-db-data:/var/lib/mysql
    networks:
      - chat-youapp-network

volumes:
  user-db-data:
  auth-db-data:

networks:
  chat-youapp-network:
    driver: bridge
